main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include, handler404, handler500

app_name = 'main'


urlpatterns = [
    path('<lang>/', views.HomeView.as_view(), name='home_url'),
    path('<lang>/about', views.AboutView.as_view(), name='about _url'),
    path('<lang>/contacts/', views.ContactsView.as_view(), name='home_contact'),
    path('<lang>/news/', views.PostView.as_view(), name='news_url'),
    path('<lang>/news/<int:id>', views.PostDetailView.as_view(), name='post_detail_url'),
    path('<lang>/product/', views.ProductView.as_view(), name='product_url'),
    # path('<lang>/search/', views.ProductSearchView.as_view(), name='product_search_url'),
    path('<lang>/search/', views.SearchView.as_view(), name='product_search_url'),
    path('<lang>/product/<slug:category_slug>/', views.ProductByCategory.as_view(), name='product_by_category_url'),
    path('<lang>/product/<int:id>', views.ProductDetailView.as_view(), name='product_detail_url'),
    path('<lang>/gallery/', views.GalleryView.as_view(), name='gallery_url'),
    path('<lang>/gallery/<int:id>', views.GalleryDetail.as_view(), name='gallery_detail_url'),
    path('<lang>/video', views.VideoView.as_view(), name='video_url'),
    path('<lang>/static/<int:id>', views.StaticDetail.as_view(), name="static-detail"),
    path('<lang>/leader/', views.LeaderList.as_view(), name="leader-url"),
    path('<lang>/enterprise/', views.EnterpriseList.as_view(), name="enterprise_url"),
    path('<lang>/veterans/', views.VeteransList.as_view(), name="veterans_url"),
    path('<lang>/chairmen/', views.ChairmenList.as_view(), name="chairmen_url"),
    path('<lang>/poultry/', views.PoultryTypeView.as_view(), name="poultry_url"),
    path('<lang>/poultry/<int:id>', views.PoultryDetailView.as_view(), name='poultry_detail_url'),
]

parranda_sanoat/urls.py
import patterns as patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns

from . import settings
from main import views as main_views


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
)

urlpatterns += [
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

handler500 = 'main.views.error_500'
handler404 = 'main.views.error_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/search_results.html
{% extends "base/base.html" %}
{% load i18n app_tags %}

{% block styles %}
    {{ block.super }}
    <style>
        .search-field {
            display: inline-block;
            width: auto;
        }

        .search-button {
            font-size: 13px;
            color: #fff;
            text-transform: uppercase;
            border-radius: 100px;
            background-color: #182b8c;
            border: 2px solid #182b8c;
            padding: 7px 40px;
        }


    </style>
{% endblock %}

{% block content %}

    <section class="contacts-page">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <div class="form-content">
                        {#                        <h3 class="page-title">{% trans 'Search' %}</h3>#}

                        <form class="form-group d-flex" action="{% url 'main:product_search_url' LANGUAGE_CODE %}"
                              method="get">
                            <input type="text" name="search" class="form-control search-field"
                                   placeholder="{% trans "Your query" %}" required="" value="{{ request.GET.search }}">
                            <button class="search-button ml-2 btn btn-info" type="submit">{% trans "Search" %}</button>
                        </form>

                    </div>

                    <div class="heading-box contacts-heading">
                        <h1 class="heading">{% trans "Search results" %}: {{ request.GET.search }}</h1>
                        <hr>
                    </div>

                    <div class="search">

                        {% if types %}
                            <ul>

                                {% for item in types %}
                                    <div>
                                        <h4 style="font-size: 26px">{{ item }}</h4>

                                        {% for obj in types|get_prop:item %}
                                            <h5><a href="{{ obj.link }}">{{ obj.title|safe|truncatewords_html:10 }}</a>
                                            </h5>
                                        {% endfor %}
                                        <p>&nbsp;</p>
                                    </div>

                                {% endfor %}

                            </ul>
                        {% else %}
                            <p class="text-danger" style="font-size: 26px">{% trans "No data found" %}</p>
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
    </section>

{% endblock %}