main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include, handler404, handler500

app_name = 'main'


urlpatterns = [
    path('<lang>/', views.HomeView.as_view(), name='home_url'),
    path('<lang>/about', views.AboutView.as_view(), name='about _url'),
    path('<lang>/contacts/', views.ContactsView.as_view(), name='home_contact'),
    path('<lang>/news/', views.PostView.as_view(), name='news_url'),
    path('<lang>/news/<int:id>', views.PostDetailView.as_view(), name='post_detail_url'),
    path('<lang>/product/', views.ProductView.as_view(), name='product_url'),
    # path('<lang>/search/', views.ProductSearchView.as_view(), name='product_search_url'),
    path('<lang>/search/', views.SearchView.as_view(), name='product_search_url'),
    path('<lang>/product/<slug:category_slug>/', views.ProductByCategory.as_view(), name='product_by_category_url'),
    path('<lang>/product/<int:id>', views.ProductDetailView.as_view(), name='product_detail_url'),
    path('<lang>/gallery/', views.GalleryView.as_view(), name='gallery_url'),
    path('<lang>/gallery/<int:id>', views.GalleryDetail.as_view(), name='gallery_detail_url'),
    path('<lang>/video', views.VideoView.as_view(), name='video_url'),
    path('<lang>/static/<int:id>', views.StaticDetail.as_view(), name="static-detail"),
    path('<lang>/leader/', views.LeaderList.as_view(), name="leader-url"),
    path('<lang>/enterprise/', views.EnterpriseList.as_view(), name="enterprise_url"),
    path('<lang>/veterans/', views.VeteransList.as_view(), name="veterans_url"),
    path('<lang>/chairmen/', views.ChairmenList.as_view(), name="chairmen_url"),
    path('<lang>/poultry/', views.PoultryTypeView.as_view(), name="poultry_url"),
    path('<lang>/poultry/<int:id>', views.PoultryDetailView.as_view(), name='poultry_detail_url'),
]

parranda_sanoat/urls.py
import patterns as patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns

from . import settings
from main import views as main_views


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
)

urlpatterns += [
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

handler500 = 'main.views.error_500'
handler404 = 'main.views.error_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/news/all_news.html
{% extends 'base/base.html' %}
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %} {% trans 'News' %} | {% trans 'Parranda industry' %} {% endblock title %}
{% block og_title %} {% trans 'News' %} {% endblock og_title %}

{% block content %}

    <section id="home" class="home d-flex justify-content-center align-items-end" style="background-image: url('../../static/img/home.png');">
    </section>

    <section id="news" class="news news-list">
        <div class="container">
            <div class="news-title d-flex justify-content-center align-items-center flex-column">
                <h2 class="section-title">{% trans 'All news' %}</h2>
                <div class="underline"></div>
            </div>
            <div class="news-content row justify-content-center align-items-center flex-column">
                <div class="row justify-content-between align-items-center w-100">
                    {% for new in news %}

                        <div class="card-list">
                            <img src="{{ new.main_image.url }}" alt="" class="col-md-6 p-0 img-news">
                            <div class="card-list__content col-md-6">
                                <div class="card-title">{{ new.title }}</div>
                                <p class="card-article">{{ new.description|safe }}</p>
                                <div class="card-date">{{ new.created|date:"d M Y" }}</div>
                                <div><a href="{% url 'main:post_detail_url' LANGUAGE_CODE new.id %}"
                                        class="btn-main-over">{% trans 'Read more' %}<i class="fas fa-arrow-right ml-2"></i></a>
                                </div>
                                <img src="{% static 'img/egg.png' %}" alt="" width="50px" height="auto" class="egg-el">
                            </div>
                        </div>
                    {% endfor %}
                </div>


            </div>


            {% if is_paginated %}
                <div class="pagers text-center" role="toolbar" aria-label="Toolbar with button groups">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}" type="button"
                           class="btn btn-danger mr-3">{% trans 'Prev' %}</a>
                    {% endif %}
                    <div class="btn-group me-2" role="group" aria-label="First group">
                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <a class="btn btn-danger">{{ i }}</a>
                            {% else %}
                                <a href="?page={{ i }}" class="btn btn-outline-danger">{{ i }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}"
                           class="btn btn-danger ml-3">{% trans 'Next' %}</a>
                    {% endif %}
                </div>
            {% endif %}


        </div>
    </section>

{% endblock content %}

templates/pages/news/new_detail.html
{% extends 'base/base.html' %}
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %} {% trans 'Static' %} | {% trans 'Parranda industry' %}{% endblock title %}

{% block content %}

    <section id="home" class="home d-flex justify-content-center align-items-end"
             style="background-image: url('{% static "/img/home.png" %}');">
    </section>

    <section class="news-detail">
        <div class="container">
            <img class="img-fluid mb-3" src="{{ object.main_image.url }}" alt="{{ object.title }}"
                 style="width: 100%;height: 500px;object-fit: cover; border-radius: 10px;">
            <div class="news-date">{{ object.created|date:"d M Y" }}</div>
            <div class="news-detail__title">
                <h3>{{ object.title }}</h3>
                <div class="news-detail__title__line"></div>

            </div>

            <div class="news-detail__description">
                <p>{{ object.content|safe }}</p>
            </div>
            <div class="news-detail__info">
                <div class="d-flex justify-content-between align-items-center">
                    <span class="view-block"><i class="fas fa-eye mr-2"></i>{{ object.view_count }}</span>
                    <button id="print-btn" class="btn-main"><i class="fas fa-print mr-2"></i>{% trans 'PRINT' %}
                    </button>
                </div>
            </div>
            <div class="news-detail__social">
                <div class="row justify-content-around align-items-center" style="width: 60%;margin: 0 auto;">

                    {% with base_url="http://parrandasanoat.uz/" %}

                        <button class="btn-main-over news-detail__social__button"><a href="#">
                            <i class="fas fa-share mr-2"></i>{% trans 'share' %}</a></button>

                        <button class="btn-main-over news-detail__social__button"><a
                                href="https://www.facebook.com/sharer/sharer.php?u=
                                        {{ base_url }}{{ request.get_full_path }}&t={{ object.title }}">
                            <i class="fab fa-facebook-f mr-2"></i>{% trans 'Facebook' %}</a></button>

                        <button class="btn-main-over news-detail__social__button"><a
                                href="https://twitter.com/share?text={{ object.title }}&url=
                                        {{ base_url }}{{ request.get_full_path }}">
                            <i class="fab fa-twitter mr-2"></i>{% trans 'Twitter' %}</a></button>

                        <button class="btn-main-over news-detail__social__button"><a
                                href="https://telegram.me/share/url?url=
                                        {{ base_url }}{{ request.get_full_path }}&text={{ object.title }}">
                            <i class="fab fa-telegram mr-2"></i>{% trans 'Telegram' %}</a></button>
                    {% endwith %}

                </div>
            </div>
        </div>
    </section>
{% endblock content %}


{% block custom_style %}
    <style>

        @media print {

            .news-detail__img {
                display: none !important;
            }

            .home {
                display: none !important;
            }

            .btn-main {
                display: none !important;
            }

            .view-block {
                display: none !important;
            }

            .home-title {
                display: none !important;
            }

            .news-detail__social {
                display: none !important;
            }

            .header {
                display: none !important;
            }

            .footer {
                display: none !important;
            }

            .globalClass_6a91 {
                display: none !important;
            }

        }

    </style>
{% endblock %}