main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include, handler404, handler500

app_name = 'main'


urlpatterns = [
    path('<lang>/', views.HomeView.as_view(), name='home_url'),
    path('<lang>/about', views.AboutView.as_view(), name='about _url'),
    path('<lang>/contacts/', views.ContactsView.as_view(), name='home_contact'),
    path('<lang>/news/', views.PostView.as_view(), name='news_url'),
    path('<lang>/news/<int:id>', views.PostDetailView.as_view(), name='post_detail_url'),
    path('<lang>/product/', views.ProductView.as_view(), name='product_url'),
    # path('<lang>/search/', views.ProductSearchView.as_view(), name='product_search_url'),
    path('<lang>/search/', views.SearchView.as_view(), name='product_search_url'),
    path('<lang>/product/<slug:category_slug>/', views.ProductByCategory.as_view(), name='product_by_category_url'),
    path('<lang>/product/<int:id>', views.ProductDetailView.as_view(), name='product_detail_url'),
    path('<lang>/gallery/', views.GalleryView.as_view(), name='gallery_url'),
    path('<lang>/gallery/<int:id>', views.GalleryDetail.as_view(), name='gallery_detail_url'),
    path('<lang>/video', views.VideoView.as_view(), name='video_url'),
    path('<lang>/static/<int:id>', views.StaticDetail.as_view(), name="static-detail"),
    path('<lang>/leader/', views.LeaderList.as_view(), name="leader-url"),
    path('<lang>/enterprise/', views.EnterpriseList.as_view(), name="enterprise_url"),
    path('<lang>/veterans/', views.VeteransList.as_view(), name="veterans_url"),
    path('<lang>/chairmen/', views.ChairmenList.as_view(), name="chairmen_url"),
    path('<lang>/poultry/', views.PoultryTypeView.as_view(), name="poultry_url"),
    path('<lang>/poultry/<int:id>', views.PoultryDetailView.as_view(), name='poultry_detail_url'),
]

parranda_sanoat/urls.py
import patterns as patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns

from . import settings
from main import views as main_views


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
)

urlpatterns += [
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

handler500 = 'main.views.error_500'
handler404 = 'main.views.error_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/gallery/all_gallery.html
{% extends 'base/base.html' %}
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %} {% trans 'Gallery' %} | {% trans 'Parranda industry ' %}{% endblock title %}
{% block og_title %} {% trans 'Gallery' %} {% endblock og_title %}

{% block content %}
    <section id="home" class="home d-flex justify-content-center align-items-end" style="background-image: url('{% static "img/home.png" %}');">
    </section>
    <section id="gallery" class="gallery-list">
        <div class="gallery-bg" style="background-color: #F4F4F4;">
            <div class="container">
                <div class="gallery-title">
                    <h2 class="section-title">{% trans 'GALLERY' %}</h2>
                    <div class="underline"></div>
                </div>
                <div class="gallery-content">
            <div class="row">
                {% for gallery in galleries %}
                    <div class="col-md-4" data-aos="fade-right">
                        <div class="photo" style="background-image: url('{{ gallery.image.url }}');
                                ">
                            <a href="{% url 'main:gallery_detail_url' LANGUAGE_CODE gallery.id %}"
                               class="photo-area">{{ gallery.title }}
                            </a></div>
                    </div>
                {% endfor %}
            </div>
        </div>
            </div>
            <div class="pagers text-center" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group me-2" role="group" aria-label="First group">

                    {% if is_paginated %}
                        <div class="pagers text-center" role="toolbar" aria-label="Toolbar with button groups">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}" type="button"
                                   class="btn btn-danger mr-3">{% trans 'Prev' %}</a>
                            {% endif %}
                            <div class="btn-group me-2" role="group" aria-label="First group">
                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <a class="btn btn-danger">{{ i }}</a>
                                    {% else %}
                                        <a href="?page={{ i }}" class="btn btn-outline-danger">{{ i }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}"
                                   class="btn btn-danger ml-3">{% trans 'Next' %}</a>
                            {% endif %}
                        </div>
                    {% endif %}


                </div>
            </div>
        </div>
    </section>


{% endblock content %}

templates/pages/gallery/gallery_detail.html
{% extends 'base/base.html' %}
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}
    <div class="container">
        <div class="row py-5 pt-lg-5">
            <div class="col-md-6">
                <img style="width: 100%;" src="{{ object.image.url }}" alt="img">
            </div>
            <div class="col-md-6">
                <h2>
                    {{ object.title }}
                </h2>
                <p>
                    {{ object.content|safe }}
                </p>
            </div>
                    {% for gallery in object.sub_galleries.all %}

            <div class="col-md-3 mt-5">
                <div class="card-deck">
                        <div class="card p-0">
                            <div class="img-gallery"
                                 style="background-image: url('{{ gallery.image.url }}');">
                                <a data-fancybox="gallery" href="{{ gallery.image.url }}"
                                   class="photo-area">

                                    {% if gallery.title %}
                                        {{ gallery.title }}
                                    {% endif %}
                                </a>
                            </div>
                        </div>

                </div>
            </div>
                            {% endfor %}

        </div>
    </div>
{% endblock content %}